---
public_domain: ajak.xyz
wg_domain: "wg.{{ public_domain }}"
repo_root: https://git.ajak.xyz/ajak
consul_api_root: "http://consul.{{ public_domain }}"
this_repo: "{{ repo_root }}/ansible"
secrets_repo: "{{ repo_root }}/ansible-secrets"
timezone: US/Pacific
my_email: jchelmert3@posteo.net
whoami: jake
gccarch: x86-64
getpkg: true
smtp_host: "sirius.{{ public_domain }}"

# TODO: surely a way to grab these straight out of repositories.xml
gentoo_repos:
  gentoo:
    source: https://github.com/gentoo-mirror/gentoo
    extra_lines: |
      auto-sync = yes
      sync-git-verify-commit-signature = yes
      volatile = no
  ajak:
    source: https://gitlab.com/ajak/ajak
  guru:
    source: https://github.com/gentoo-mirror/guru.git

repos:
  - gentoo

world:
  - app-admin/eclean-kernel
  - app-misc/tmux
  - app-text/wgetpaste
  - dev-debug/strace
  - net-analyzer/tcpdump

my_roles:
  - hosts
  - sshd
  - sudo
  - timezone
  - fstab
  - automount
  - python_exec
  - networkd
  - resolved
  - zfs
  - smartd
  - portage
  - portage_update
  - firewalld
  - ansible_pull
  - kernel
  - podman_gentoo
  - dnsmasq
  - unbound
  - dnscrypt_proxy
  - greetd
  - binhost
  - node_exporter
  - postfix
  - nullmailer
  - prometheus
  - gitea
  - podman
  - transmission
  - speedtest_exporter
  - nut
  - dotfiles
  - services
  - docker
  - dnsserver
  - grafana
  - grub
  # - password_store
  - groups
  - u2f_keys
  - firefox
  - tor
  - consul
  - sysctl
