---
repo_root: http://git.wg.home.arpa/ajak
this_repo: "{{ repo_root }}/ansible"
secrets_repo: "{{ repo_root }}/ansible-secrets"
timezone: US/Central
node_exporter_port: 9100
services:
  - systemd-timesyncd
my_domain: home.arpa
public_domain: ajak.xyz
my_email: jchelmert3@posteo.net
gccarch: x86-64
getpkg: true
dns_server: 10.5.0.1
libvirt_bridge: virbr0

# TODO: surely a way to grab these straight out of repositories.xml
gentoo_repos:
  gentoo:
    source: https://github.com/gentoo-mirror/gentoo
    extra_lines: |
     auto-sync = yes
     sync-git-verify-commit-signature = yes
     sync-depth = 1
  ajak:
    source: https://gitlab.com/ajak/ajak

repos:
  - gentoo

# Some default-off's so I don't have to care if a var is defined
ansible_pull: false
dnscryptproxy: false
dotsecrets: false
dnsmasq: false
filesystems: {}
gitea: false
host_network_mounts: []
host_repos: []
host_services: []
host_stopservices: []
network_mounts: []
nfsrepo: false
nginx: false
podman_gentoo: false
portage_git: false
postfix: false
prometheus: false
resolved: true
stopservices: []
zfs: false
