---
public_domain: ajak.xyz
wg_domain: "wg.{{ public_domain }}"
repo_root: https://git.ajak.xyz/ajak
consul_api_root: "http://consul.{{ public_domain }}"
this_repo: "{{ repo_root }}/ansible"
secrets_repo: "{{ repo_root }}/ansible-secrets"
timezone: US/Pacific
my_email: jchelmert3@posteo.net
whoami: jake
gccarch: x86-64
getpkg: true
smtp_host: "sirius.{{ public_domain }}"
consul_client: false
consul_server: false

# TODO: surely a way to grab these straight out of repositories.xml
gentoo_repos:
  gentoo:
    source: https://github.com/gentoo-mirror/gentoo
    extra_lines: |
      auto-sync = yes
      sync-git-verify-commit-signature = yes
      volatile = no
  ajak:
    source: https://gitlab.com/ajak/ajak
  guru:
    source: https://github.com/gentoo-mirror/guru.git

world:
  - app-admin/eclean-kernel
  - app-misc/tmux
  - app-text/wgetpaste
  - dev-debug/strace
  - net-analyzer/tcpdump
  - sys-block/parted

binhost_world:
  - "{{ world }}"

portage_configuration:
  x86_64:
    env:
    make.profile: default/linux/amd64/17.1/systemd/merged-usr
    package.accept_keywords:
      - app-admin/ananicy  # bug 891629
      - app-metrics/postfix_exporter
      - app-admin/podman-gentoo::ajak:
          - "**"
      - app-crypt/lego::guru
    package.env:
    package.license:
      - sys-kernel/linux-firmware:
          - linux-fw-redistributable
          - no-source-code
      - sys-firmware/intel-microcode:
          - intel-ucode
      - sys-block/perccli:
          - Avago
    package.mask:
      - "*/*::musl"
      - "*/*::ajak"
      - "*/*::pentoo"
      - "*/*::guru"
    package.unmask:
      - app-crypt/lego::guru
      - app-admin/podman-gentoo::ajak
    package.use:  # todo: finish
      firewalld:
        - net-firewall/nftables:
            - xtables
            - json
            - python
      gentoo-kernel:
        - "*/*":
            - dist-kernel
        - sys-kernel/gentoo-kernel:
            - hardened
        - sys-kernel/installkernel:
            - dracut
            - grub
            - systemd
      ldap:
        - app-crypt/mit-krb5:
            - openldap
        - sys-auth/sssd:
            - sudo
        - dev-libs/cyrus-sasl:
            - kerberos
        - net-nds/openldap:
            - experimental
            - sasl
        - net-dns/bind-tools:
            - gssapi
      libvirt:
        - net-libs/gnutls:
            - pkcs11
            - tools
      openvswitch:
        - sys-apps/util-linux:
            - caps
      ossec:
        - net-analyzer/ossec-hids:
            - agent
      podman:
        - net-firewall/iptables:
            - nftables
      systemd:
        - sys-apps/systemd:
            - boot
            - cryptsetup
            - curl
            - gnuefi
            - elfutils
            - kernel-install
            - tpm
            - importd
            - lzma
            - ukify
    repos.conf:
      gentoo:
        sync-type: git
        sync-depth: 1
        location: "{{ gentoo_repo_base }}/gentoo"
        sync-uri: https://github.com/gentoo-mirror/gentoo
        auto-sync: "yes"
        sync-git-verify-commit-signature: "yes"
        volatile: "no"
      guru:
        sync-type: git
        sync-depth: 1
        location: "{{ gentoo_repo_base }}/guru"
        sync-uri: https://github.com/gentoo-mirror/guru.git
        volatile: "no"

my_roles:
  - hosts
  - sshd
  - sudo
  - timezone
  - fstab
  - automount
  - python_exec
  - networkd
  - resolved
  - zfs
  - smartd
  - portage
  - portage_update
  - firewalld
  - ansible_pull
  - kernel
  - podman_gentoo
  - dnsmasq
  - unbound
  - dnscrypt_proxy
  - greetd
  - binhost
  - node_exporter
  - postfix
  - nullmailer
  - prometheus
  - gitea
  - podman
  - transmission
  - speedtest_exporter
  - nut
  - dotfiles
  - services
  - docker
  - dnsserver
  - grafana
  - grub
  # - password_store
  - groups
  - u2f_keys
  - firefox
  - tor
  - consul
  - sysctl
