---
public_domain: ajak.xyz
wg_domain: "wg.{{ public_domain }}"
repo_root: https://git.ajak.xyz/ajak
this_repo: "{{ repo_root }}/ansible"
secrets_repo: "{{ repo_root }}/ansible-secrets"
timezone: US/Central
node_exporter_port: 9100
system_services_all:
  - systemd-timesyncd
my_email: jchelmert3@posteo.net
whoami: jake
gccarch: x86-64
getpkg: true
dns_server: 192.168.1.213
smtp_host: "sirius.{{ wg_domain }}"
libvirt_bridge: virbr0

# TODO: surely a way to grab these straight out of repositories.xml
gentoo_repos:
  gentoo:
    source: https://github.com/gentoo-mirror/gentoo
    extra_lines: |
      auto-sync = yes
      sync-git-verify-commit-signature = yes
  ajak:
    source: https://gitlab.com/ajak/ajak

repos:
  - gentoo

world:
  - app-text/wgetpaste

# Some default-off's so I don't have to care if a var is defined
ansible_pull: false
dnscryptproxy: false
dotsecrets: false
dnsmasq: false
filesystems: {}
host_repos: []
nfsrepo: false
nginx: false
podman_gentoo: false
portage_git: false
postfix: false
prometheus: false
resolved: true
zfs: false
