---
public_domain: ajak.xyz
wg_domain: "wg.{{ public_domain }}"
repo_root: https://git.ajak.xyz/ajak
this_repo: "{{ repo_root }}/ansible"
secrets_repo: "{{ repo_root }}/ansible-secrets"
timezone: US/Central
my_email: jchelmert3@posteo.net
whoami: jake
gccarch: x86-64
getpkg: true
smtp_host: "sirius.{{ wg_domain }}"

# TODO: surely a way to grab these straight out of repositories.xml
gentoo_repos:
  gentoo:
    source: https://github.com/gentoo-mirror/gentoo
    extra_lines: |
      auto-sync = yes
      sync-git-verify-commit-signature = yes
  ajak:
    source: https://gitlab.com/ajak/ajak

repos:
  - gentoo

world:
  - app-text/wgetpaste

my_roles:
  - hosts
  - sshd
  - sudo
  - timezone
  - fstab
  - networkd
  - resolved
  - zfs
  - smartd
  - portage
  - python_exec
  - ansible_pull
  - podman_gentoo
  - dnsmasq
  - unbound
  - dnscrypt_proxy
  - greetd
  - binhost
  - node_exporter
  - postfix
  - nullmailer
  - prometheus
  - gitea
  - portage_update
  - podman
  - transmission
  - speedtest_exporter
  - dotfiles
  - services
  - docker
  - dnsserver
  - grafana
  - grub
  # - password_store
  - groups
  - u2f_keys
  - firefox
  - tor
  - consul

# Some default-off's so I don't have to care if a var is defined
portage_git: false
postfix: false
prometheus: false
resolved: true
zfs: false
