---
public_domain: ajak.xyz
wg_domain: "wg.{{ public_domain }}"
repo_root: https://git.ajak.xyz/ajak
consul_api_root: "http://consul.{{ public_domain }}"
this_repo: "{{ repo_root }}/ansible"
secrets_repo: "{{ repo_root }}/ansible-secrets"
timezone: US/Pacific
my_email: jchelmert3@posteo.net
whoami: jake
gccarch: x86-64
getpkg: true
smtp_host: "sirius.{{ public_domain }}"
consul_client: false
consul_server: false

# TODO: surely a way to grab these straight out of repositories.xml
gentoo_repos:
  gentoo:
    source: https://github.com/gentoo-mirror/gentoo
    extra_lines: |
      auto-sync = yes
      sync-git-verify-commit-signature = yes
      volatile = no
  ajak:
    source: https://gitlab.com/ajak/ajak
  guru:
    source: https://github.com/gentoo-mirror/guru.git

world:
  - app-admin/consul
  - app-admin/eclean-kernel
  - app-admin/sudo
  - app-editors/emacs
  - app-editors/vim
  - app-metrics/node_exporter
  - app-misc/tmux
  - app-portage/gentoolkit
  - app-portage/portage-utils
  - app-shells/bash-completion
  - app-text/wgetpaste
  - dev-debug/gdb
  - dev-debug/strace
  - net-analyzer/mtr
  - net-analyzer/tcpdump
  - sys-apps/usbutils
  - sys-block/parted
  - sys-kernel/gentoo-kernel
  - sys-process/htop
  - sys-process/lsof

_binhost_world:
  - app-admin/ananicy
  - app-admin/ansible
  - app-admin/consul
  - app-admin/eclean-kernel
  - app-admin/lib_users
  - app-admin/podman-gentoo
  - app-admin/spectre-meltdown-checker
  - app-admin/stow
  - app-admin/sudo
  - app-antivirus/clamav
  - app-containers/docker
  - app-containers/docker-cli
  - app-containers/docker-compose
  - app-containers/podman
  - app-crypt/lego
  - app-crypt/sbctl
  - app-crypt/sbsigntools
  - app-crypt/tpm2-tools
  - app-doc/eclass-manpages
  - app-editors/emacs
  - app-editors/vim
  - app-emulation/libvirt
  - app-emulation/qemu
  - app-emulation/virt-manager
  - app-eselect/eselect-repository
  - app-forensics/rkhunter
  - app-metrics/node_exporter
  - app-metrics/postfix_exporter
  - app-misc/jq
  - app-misc/resolve-march-native
  - app-misc/screen
  - app-misc/tmux
  - app-portage/cpuid2cpuflags
  - app-portage/eix
  - app-portage/gentoolkit
  - app-portage/portage-utils
  - app-portage/smart-live-rebuild
  - app-shells/bash-completion
  - app-text/wgetpaste
  - dev-debug/gdb
  - dev-debug/strace
  - dev-python/docker
  - dev-tcltk/expect
  - dev-vcs/git
  - dev-vcs/subversion
  - mail-client/mutt
  - mail-mta/postfix
  - net-analyzer/fail2ban
  - net-analyzer/iftop
  - net-analyzer/mtr
  - net-analyzer/nettop
  - net-analyzer/nmap
  - net-analyzer/ossec-hids
  - net-analyzer/speedtest-cli
  - net-analyzer/tcpdump
  - net-analyzer/traceroute
  - net-dns/bind-tools
  - net-firewall/firewalld
  - net-fs/nfs-utils
  - net-misc/apt-cacher-ng
  - net-misc/mosh
  - net-misc/openvswitch
  - net-misc/socat
  - net-misc/whois
  - net-misc/yt-dlp
  - net-nds/openldap
  - net-proxy/mitmproxy
  - net-vpn/tor
  - net-vpn/wireguard-tools
  - sys-apps/edac-utils
  - sys-apps/ipmitool
  - sys-apps/iucode_tool
  - sys-apps/lshw
  - sys-apps/merge-usr
  - sys-apps/pkgcore
  - sys-apps/portage
  - sys-apps/smartmontools
  - sys-apps/usbutils
  - sys-auth/sssd
  - sys-block/nbd
  - sys-block/perccli
  - sys-boot/grub:2
  - sys-firmware/intel-microcode
  - sys-fs/btrfs-progs
  - sys-fs/cryptsetup
  - sys-fs/dosfstools
  - sys-fs/ntfs3g
  - sys-fs/xfsprogs
  - sys-fs/zfs
  - sys-fs/zfs-kmod
  - sys-kernel/gentoo-kernel
  - sys-kernel/installkernel
  - sys-kernel/linux-firmware
  - sys-power/nut
  - sys-process/cronie
  - sys-process/glances
  - sys-process/htop
  - sys-process/iotop
  - sys-process/lsof
binhost_world: "{{ _binhost_world + world }}"

portage_configuration:
  x86_64:
    env:
    make.profile: default/linux/amd64/17.1/systemd/merged-usr
    package.accept_keywords:
      - app-admin/ananicy  # bug 891629
      - app-metrics/postfix_exporter
      - app-admin/podman-gentoo::ajak:
          - "**"
      - app-crypt/lego::guru
    package.env:
    package.license:
      - sys-kernel/linux-firmware:
          - linux-fw-redistributable
          - no-source-code
      - sys-firmware/intel-microcode:
          - intel-ucode
      - sys-block/perccli:
          - Avago
    package.mask:
      - "*/*::musl"
      - "*/*::ajak"
      - "*/*::pentoo"
      - "*/*::guru"
    package.unmask:
      - app-crypt/lego::guru
      - app-admin/podman-gentoo::ajak
    package.use:  # todo: finish
      firewalld:
        - net-firewall/nftables:
            - xtables
            - json
            - python
      gentoo-kernel:
        - "*/*":
            - dist-kernel
        - sys-kernel/gentoo-kernel:
            - hardened
        - sys-kernel/installkernel:
            - dracut
            - grub
            - systemd
      ldap:
        - app-crypt/mit-krb5:
            - openldap
        - sys-auth/sssd:
            - sudo
        - dev-libs/cyrus-sasl:
            - kerberos
        - net-nds/openldap:
            - experimental
            - sasl
        - net-dns/bind-tools:
            - gssapi
      libvirt:
        - net-libs/gnutls:
            - pkcs11
            - tools
      openvswitch:
        - sys-apps/util-linux:
            - caps
      ossec:
        - net-analyzer/ossec-hids:
            - agent
      mitmproxy:
        - app-arch/brotli:
            - python
      podman:
        - net-firewall/iptables:
            - nftables
      rkhunter:
        - sys-process/lsof:
            - rpc
      systemd:
        - sys-apps/systemd:
            - boot
            - cryptsetup
            - curl
            - gnuefi
            - elfutils
            - kernel-install
            - tpm
            - importd
            - lzma
            - ukify
    repos.conf:
      gentoo:
        sync-type: git
        sync-depth: 1
        location: "{{ gentoo_repo_base }}/gentoo"
        sync-uri: https://github.com/gentoo-mirror/gentoo
        auto-sync: "yes"
        sync-git-verify-commit-signature: "yes"
        volatile: "no"
      guru:
        sync-type: git
        sync-depth: 1
        location: "{{ gentoo_repo_base }}/guru"
        sync-uri: https://github.com/gentoo-mirror/guru.git
        volatile: "no"

my_roles:
  - hosts
  - sshd
  - sudo
  - timezone
  - fstab
  - automount
  - python_exec
  - networkd
  - resolved
  - zfs
  - smartd
  - portage
  - portage_update
  - firewalld
  - ansible_pull
  - kernel
  - podman_gentoo
  - dnsmasq
  - unbound
  - dnscrypt_proxy
  - greetd
  - binhost
  - node_exporter
  - postfix
  - nullmailer
  - prometheus
  - gitea
  - podman
  - transmission
  - speedtest_exporter
  - nut
  - dotfiles
  - services
  - docker
  - dnsserver
  - grafana
  - grub
  # - password_store
  - groups
  - u2f_keys
  - firefox
  - tor
  - consul
  - sysctl
