---
group_system_services:
  - node_exporter

internal_interfaces:
  - enp1s0
trusted_interface:
  - enp2s0
consul_client_bind_ip: |-
  {{ hostvars[inventory_hostname]['ansible_' + trusted_interface].ipv4.address }}
