---
- name: Collect netmounts variables
  ansible.builtin.set_fact:
    netmounts_vars: "{{ q('ansible.builtin.varnames', 'netmounts') }}"
- name: Collect netmounts
  ansible.builtin.set_fact:
    network_mounts: "{{ lookup('ansible.builtin.vars', *netmounts_vars) }}"
- name: Create dirs for network mounts
  ansible.builtin.file:
    path: /network/{{ item['target'] }}
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items: "{{ network_mounts }}"
- name: Deploy fstab
  ansible.builtin.template:
    src: fstab.j2
    dest: /etc/fstab
    owner: root
    group: root
    mode: 0644
