---
- name: Copy zfs cron jobs
  when: zfs
  ansible.builtin.copy:
    src: etc/{{ item }}
    dest: /etc
    owner: root
    group: root
    mode: "0744"
  with_items:
    - cron.d
    - cron.hourly
    - cron.daily
    - cron.weekly
    - cron.monthly
- name: Start and enable zfs services
  when: zfs
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - zfs-import-cache.service
    - zfs-mount.service
    - zfs-share.service
    - zfs-zed.service
    - zfs-volume-wait.service
    - zfs.target
