---
- name: Remove zfs cron jobs
  # unconditionally do this now that all of that functionality is
  # handled by the systemd services/timers
  ansible.builtin.file:
    path: "/etc/{{ item }}"
    state: absent
  loop: "{{ zfs_cronjobs }}"
- name: Start and enable zfs services
  when: zfs_pools
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ zfs_services }}"
- name: Start and enable zfs timers
  when: zfs_pools
  ansible.builtin.service:
    name: "zfs-scrub-monthly@{{ item }}.timer"
    state: started
    enabled: true
  loop: "{{ zfs_pools }}"
- name: Remove zfs configuration
  when: not zfs_pools
  ansible.builtin.include_tasks: remove.yml
