---
- name: Copy zfs cron jobs
  when: zfs
  ansible.builtin.copy:
    src: etc/{{ item }}
    dest: /etc
    owner: root
    group: root
    mode: "0744"
  with_items:
    - cron.d
    - cron.hourly
    - cron.daily
    - cron.weekly
    - cron.monthly
