---
- name: Populate service facts
  ansible.builtin.service_facts:
- name: Stop and disable zfs services
  when: item in ansible_facts.services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ zfs_services }}"
