---
- name: regenerate generic.db
  ansible.builtin.command:
    cmd: postmap /etc/postfix/generic
- name: regenerate password.db
  ansible.builtin.command:
    cmd: postmap /etc/postfix/password
- name: restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
