---
- name: Regenerate generic.db
  ansible.builtin.command:  # noqa no-changed-when
    cmd: postmap /etc/postfix/generic
- name: Regenerate password.db
  ansible.builtin.command:  # noqa no-changed-when
    cmd: postmap /etc/postfix/password
- name: Restart postfix_exporter
  ansible.builtin.service:
    name: postfix_exporter
    state: restarted
- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
