---
- name: install nullmailer configuration
  notify: restart nullmailer
  when: not postfix or postfix is not defined
  block:
    - name: install nullmailer remotes configuration
      ansible.builtin.copy:
        src: remotes
        dest: /etc/nullmailer/remotes
    - name: install nullmailer me configuration
      ansible.builtin.copy:
        content: "{{ ansible_hostname }}"
        dest: /etc/nullmailer/me
        mode: 0644
    - name: install nullmailer defaultdomain configuration
      ansible.builtin.copy:
        content: "{{ ansible_domain }}"
        dest: /etc/nullmailer/defaultdomain
        mode: 0644

- name: start and enable nullmailer
  when: not postfix or postfix is not defined
  ansible.builtin.service:
    name: nullmailer
    enabled: true
    state: started
