---
- name: Cleanup old files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/systemd/system/lego.service
    - /etc/systemd/system/lego.timer
    - /etc/lego.env
    - /usr/local/bin/lego-postrenew
- name: Install nginx configuration
  notify:
    - Restart nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
    validate: nginx -tc %s
- name: Enable systemd units
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
