---
# TODO: first-time run needs account generation and such
- name: Install lego timer and service file
  notify:
    - Reload systemd
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - lego.service
    - lego.timer
- name: Install secret environment file
  ansible.builtin.template:
    src: lego.env.j2
    dest: /etc/lego.env
    owner: root
    group: root
    mode: 0600
- name: Install lego post-sync script
  ansible.builtin.copy:
    src: lego-postrenew
    dest: /usr/local/bin/lego-postrenew
    owner: root
    group: root
    mode: 0755
- name: Flush handlers
  # We want the systemd state to be correct for the following plays
  ansible.builtin.meta: flush_handlers
- name: Install nginx configuration
  notify:
    - Restart nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
- name: Start lego service
  ansible.builtin.service:
    name: lego.service
    state: started
- name: Enable systemd units
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - lego.timer
    # the lego service in the previous task will generate the
    # necessary certs for nginx here
    - nginx
