---
- name: Add user's user.js
  become_user: "{{ deploy_user }}"
  ansible.builtin.copy:
    src: user.js
    dest: "~/.mozilla/firefox/{{ firefox_profile }}/user.js"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0644"
- name: Create required configuration directories
  become_user: "{{ deploy_user }}"
  ansible.builtin.file:
    path: "~/.mozilla/firefox/{{ firefox_profile }}/chrome"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0755"
    state: directory
- name: Add user's userChrome.css
  become_user: "{{ deploy_user }}"
  ansible.builtin.copy:
    src: chrome/userChrome.css
    dest: "~/.mozilla/firefox/{{ firefox_profile }}/chrome/userChrome.css"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0755"
