---
- name: Open firewall port
  ansible.builtin.include_role:
    name: firewalld_service
  vars:
    service_file: consul-exporter.xml
    service: consul-exporter
- name: Run consul exporter
  community.docker.docker_container:
    name: consul-exporter
    image: prom/consul-exporter:latest
    network_mode: host
    pull: true
    state: started
    restart_policy: unless-stopped
    command_handling: correct
    command:
      - --consul.server=http://localhost:8500
- name: Register exporter service
  ansible.builtin.include_role:
    name: consul_service
  vars:
    service: consul-exporter
    port: "{{ consul_exporter_port }}"
