---
- name: Run consul exporter
  community.docker.docker_container:
    name: consul-exporter
    image: prom/consul-exporter:latest
    network_mode: host
    pull: true
    state: started
    restart_policy: unless-stopped
    command_handling: correct
    command:
      - --consul.server=http://localhost:8500
