---
- name: Install and configure consul server
  ansible.builtin.include_tasks: server.yml
  when: consul_server
- name: Install and configure consul client
  ansible.builtin.include_tasks: client.yml
  when: consul_client
- name: Install and configure consul exporter
  ansible.builtin.include_tasks: exporter.yml
  when: consul_server or consul_client
