---
- name: Deploy the consul server
  community.docker.docker_container:
    name: consul-server
    image: hashicorp/consul
    network_mode: host
    pull: true
    state: started
    restart_policy: unless-stopped
    command_handling: correct
    command:
      - consul
      - agent
      - -server
      - -data-dir=/consul/data
      - -bootstrap-expect=1
      - "-bind={{ consul_client_bind_ip }}"
    volumes:
      - consul:/consul/data
