---
- name: Deploy the consul server
  community.docker.docker_container:
    name: consul-server
    image: hashicorp/consul:latest
    network_mode: host
    pull: true
    state: started
    restart_policy: unless-stopped
    command_handling: correct
    command:
      - consul
      - agent
      - -server
      - -data-dir=/consul/data
      - -bootstrap-expect=1
      - "-bind={{ consul_client_bind_ip }}"
      # needs the client bind address set to something accessible for
      # prometheus to access the its port 8500
      # FIXME: .. but consul_service makes requests over lo even if
      # this is bound to a public interface! why?
      - "-client={{ consul_client_bind_ip }} 127.0.0.1"
    volumes:
      - consul:/consul/data
