---
repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v24.7.0
    hooks:
      - id: ansible-lint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
