#!/usr/bin/ansible-playbook
---
- name: site.yml
  become: true
  hosts: all
  gather_facts: false
  pre_tasks:
    - include_vars:
        file: "{{ item }}"
      with_first_found:
        - "{{ inventory_hostname }}.pass.yml"
        - pass.yml
      when: usevault | default(True) | bool
      tags: always
    - setup:
      tags: always
  tasks:
    - include_role:
        name: "{{ host_role }}"
        apply:
          tags:
            - "{{ host_role }}"
      tags: always
      loop_control:
        loop_var: host_role
      loop: "{{ my_roles }}"
