#!/usr/bin/ansible-playbook
---
- name: site.yml
  become: true
  hosts: all
  gather_facts: false
  pre_tasks:
    - include_tasks: setup.yml
      tags: always
  tasks:
    - name: Run host-specific early tasks
      include_tasks: "{{ tasksfile }}"
      with_fileglob:
        - "tasks/{{ ansible_hostname }}.yml"
      loop_control:
        loop_var: tasksfile
    - name: Run global roles
      ansible.builtin.include_role:
        name: "{{ host_role }}"
        apply:
          tags:
            - "{{ host_role }}"
      tags: always
      loop_control:
        loop_var: host_role
      loop: "{{ my_roles }}"
    - name: Run host-specific roles
      when: host_roles is defined
      ansible.builtin.include_role:
        name: "{{ host_role }}"
        apply:
          tags:
            - "{{ host_role }}"
      tags: always
      loop_control:
        loop_var: host_role
      loop: "{{ host_roles }}"
