---
- name: Run speedtest_exporter
  community.docker.docker_container:
    name: speedtest_exporter
    image: miguelndecarvalho/speedtest-exporter
    pull: true
    restart_policy: unless-stopped
    state: started
    published_ports:
      - "{{ speedtest_exporter_port }}:{{ speedtest_exporter_port }}"
    exposed_ports:
      - "{{ speedtest_exporter_port }}"
