---
- name: Run speedtest_exporter
  community.docker.docker_container:
    name: speedtest_exporter
    image: miguelndecarvalho/speedtest-exporter
    pull: true
    restart_policy: unless-stopped
    state: started
    ports:
      - "{{ speedtest_exporter_bind_address }}:{{ speedtest_exporter_port }}:{{ speedtest_exporter_port }}"
- name: Allow exporter access through firewall
  ansible.posix.firewalld:
    zone: trusted
    port: "{{ speedtest_exporter_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
