---
- name: install smartd.conf
  ansible.builtin.copy:
    src: smartd.conf
    dest: /etc/smartd.conf
    owner: root
    group: root
    mode: 0644
    validate: smartd -q onecheck -c %s
- name: start and enable smartd
  ansible.builtin.service:
    name: smartd
    state: started
    enabled: true
