---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
# TODO: should probably be dependencies of the roles...
- name: Install prerequisite packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose
    - git
    - glances
    - python-docker
    - tmux
    - vim
    - wireguard-tools
- name: Enable necessary services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - docker
    - systemd-networkd
- name: Disable unecessary services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - cockpit.socket
- name: Drop cockpit from firewall
  ansible.posix.firewalld:
    zone: FedoraServer
    service: cockpit
    permanent: true
    state: disabled
    immediate: true
- name: Add wireguard firewall zone
  ansible.posix.firewalld:
    zone: trusted
    interface: wg0
    permanent: true
    state: enabled
    immediate: true
- name: Allow dns through firewall
  ansible.posix.firewalld:
    zone: FedoraServer
    service: dns
    permanent: true
    state: enabled
    immediate: true
