---
- name: Install greetd's config.toml
  when: "'desktop' in group_names"
  ansible.builtin.copy:
    src: config.toml
    dest: /etc/greetd/config.toml
    owner: root
    group: root
    mode: "0644"
