---
groups:
  - name: AllInstances
    rules:
      - alert: PrometheusTargetMissing
        expr: up == 0
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: Prometheus target missing (instance {{ $labels.instance }})
          description: "A Prometheus target has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

#       - alert: NodeTempHigh
#         expr: node_hwmon_temp_celsius{instance="raptor.wg.home.arpa:9100"} >= 80
#         for: 0m
#         labels:
#           severity: critical
#         annotations:
#           summary: Node hwmon temperature very high (instance {{ $labels.instance }})
#           description: "A node's temperature is very high. It might be overheating.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: NullmailerHighFailure
        expr: nullmailer_failed > 0
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: Nullmailer high failure (instance {{ $labels.instance }})
          description: "Nullmailer has a high failure rate here. Is it working?\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: NullmailerLargeQueue
        expr: nullmailer_queue > 0
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: Nullmailer high queue (instance {{ $labels.instance }})
          description: "Nullmailer has a large queue here. Is it working?\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
