---
- name: install dnscrypt-proxy configuration
  notify: restart dnscrypt-proxy
  when: dnscryptproxy
  block:
    - name: install dnscrypt-proxy.toml
      ansible.builtin.copy:
        src: dnscrypt-proxy.toml
        dest: /etc/dnscrypt-proxy/dnscrypt-proxy.toml
        owner: root
        group: root
        mode: 0644
- name: start and enable dnscrypt-proxy
  when: dnscryptproxy
  ansible.builtin.service:
    name: dnscrypt-proxy
    enabled: true
    state: started
