---
- name: Install podman's storage.conf
  when: podman
  notify: Reset podman state
  ansible.builtin.copy:
    src: storage.conf
    dest: /etc/containers/storage.conf
    owner: root
    group: root
    mode: "0644"
