---
# Transmission writes out its configuration when it exits, so we need
# to stop it before we change the config, else our config will be
# overwritten with the old version.
- name: Stop transmission
  ansible.builtin.service:
    name: transmission-daemon
    state: stopped
  changed_when: false
- name: Add transmission config
  notify: Restart transmission
  ansible.builtin.template:
    src: settings.json.j2
    dest: /var/lib/transmission/config/settings.json
    owner: transmission
    group: transmission
    mode: "0600"
- name: Start transmission
  ansible.builtin.service:
    name: transmission-daemon
    state: started
  changed_when: false
- name: Enable transmission
  ansible.builtin.service:
    name: transmission-daemon
    enabled: true
