---
- name: Create gitea config directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ gitea_confdir }}"
- name: Install gitea's config file
  notify: Rebuild gitea
  ansible.builtin.copy:
    src: app.ini
    # gitea uses configuration from the data directory
    dest: "{{ gitea_datadir }}/gitea/conf/app.ini"
    owner: root
    group: root
    mode: 0644
- name: Install gitea's docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ gitea_confdir }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
# Set up handling for the host's openssh to pass through to the container's:
# https://docs.gitea.io/en-us/install-with-docker/#ssh-shell-with-authorizedkeyscommand
- name: Create git's ~/.ssh
  become_user: git
  ansible.builtin.file:
    path: ~/git/.ssh"
    state: directory
    owner: "{{ git_uid }}"
    group: "{{ git_gid }}"
    mode: 0700
- name: Generate ssh key for git
  become_user: git
  openssh_keypair:
    path: ~/.ssh/id_ed25519
    type: ed25519
    size: 256
    state: present
    comment: git@{{ ansible_hostname }}
  register: ssh_key
- name: Add ssh key into gitea's authorized_keys
  ansible.builtin.lineinfile:
    path: "{{ gitea_datadir }}/git/.ssh/authorized_keys"
    line: "{{ ssh_key.public_key }}"
    owner: "{{ git_uid }}"
    group: "{{ git_gid }}"
    mode: 0600
- name: Create git ssh-shell
  ansible.builtin.copy:
    src: ssh-shell
    dest: "{{ git_home }}/ssh-shell"
    owner: "{{ git_uid }}"
    group: "{{ git_gid }}"
    mode: 0755
- name: Set git user's shell
  ansible.builtin.user:
    name: git
    shell: "{{ git_home }}/ssh-shell"
- name: Pull and start gitea
  community.docker.docker_compose:
    project_src: "{{ gitea_confdir }}"
    pull: true
    build: true
    state: present
