---
- name: install gitea configuration
  when: gitea
  notify: "restart gitea"
  copy:
    src: "{{ ansible_hostname }}.app.ini"
    dest: "/etc/gitea/app.ini"
    owner: root
    group: root
    mode: '0644'
