---
- name: Install make.conf
  ansible.builtin.copy:
    src: "{{ ansible_architecture }}/make.conf"
    dest: "{{ prefix }}/make.conf"
    owner: root
    group: root
    mode: "0644"
- name: Install world file
  ansible.builtin.copy:
    content: "{{ _world | unique | sort | join('\n') }}"
    dest: "{{ prefix }}/world"
    owner: root
    group: root
    mode: "0644"
- name: Apply portage configuration
  when: conf_type.value
  ansible.builtin.include_tasks: "{{ conf_type.key }}.yml"
  loop: "{{ _portage_configuration[ansible_architecture] | dict2items }}"
  loop_control:
    loop_var: conf_type
