---
- name: Check if gentoo repo is a git repo
  ansible.builtin.stat:
    path: "{{ gentoo_repo_base }}/gentoo/.git"
  register: repo_state
- name: Remove rsync'd gentoo repo
  when: not repo_state.stat.exists
  ansible.builtin.file:
    path: "{{ gentoo_repo_base }}/gentoo"
    state: absent
- name: Add host portage configuration
  ansible.builtin.include_tasks: add_configuration.yml
  vars:
    prefix: /etc/portage
    _portage_configuration: "{{ portage_configuration }}"
- name: Add host portage configuration
  when: podman_gentoo
  ansible.builtin.include_tasks: add_configuration.yml
  vars:
    prefix: /etc/podman-gentoo/base
    _portage_configuration: "{{ portage_configuration }}"
