---
- name: Check if gentoo repo is a git repo
  ansible.builtin.stat:
    path: "{{ gentoo_repo_base }}/gentoo/.git"
  register: repo_state
- name: Remove rsync'd gentoo repo
  when: not repo_state.stat.exists
  ansible.builtin.file:
    path: "{{ gentoo_repo_base }}/gentoo"
    state: absent
- name: Install repos
  ansible.builtin.template:
    src: repo.conf.j2
    dest: /etc/portage/repos.conf/{{ item }}.conf
    owner: root
    group: root
    mode: 0644
  with_items: "{{ repos + host_repos }}"
- name: Update make.conf
  when: inventory_hostname in groups['vms']
  ansible.builtin.template:
    src: make.conf.j2
    dest: /etc/portage/make.conf
    owner: root
    group: root
    mode: 0644
- name: Add accepted keywords
  when: ansible_hostname == 'raptor'
  block:
    - name: Create directory
      ansible.builtin.file:
        path: /etc/portage/package_accept_keywords
        state: directory
        owner: root
        group: root
        mode: 0644
    - name: Deploy accept_keywords file
      ansible.builtin.copy:
        src: package.accept_keywords
        dest: /etc/portage/package.accept_keywords/package.accept_keywords
        owner: root
        group: root
        mode: 0644
