---
- name: Check if gentoo repo is a git repo
  ansible.builtin.stat:
    path: "{{ gentoo_repo_base }}/gentoo/.git"
  register: repo_state
- name: Remove rsync'd gentoo repo
  when: not repo_state.stat.exists
  ansible.builtin.file:
    path: "{{ gentoo_repo_base }}/gentoo"
    state: absent
- name: Install repos
  ansible.builtin.template:
    src: repo.conf.j2
    dest: /etc/portage/repos.conf/{{ item }}.conf
    owner: root
    group: root
    mode: 0644
  with_items: "{{ repos + host_repos }}"
- name: Deploy portage configuration
  when: podman_gentoo or inventory_hostname in groups['vms']
  ansible.builtin.copy:
    src: "{{ ansible_architecture }}/"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: preserve
    directory_mode: 0755
    # required to copy the symlink as-is rather than copying the
    # symlink's target
    local_follow: false
  with_items:
    - "{{ ['/etc/portage'] + (['/etc/podman-gentoo/base'] if podman_gentoo else []) }}"
- name: Add world file to binhost
  when: podman_gentoo
  ansible.builtin.copy:
    src: world
    dest: /etc/podman-gentoo/base
    owner: root
    group: root
    mode: 0644
