---
- name: Check if gentoo repo is a git repo
  ansible.builtin.stat:
    path: "{{ gentoo_repo_base }}/gentoo/.git"
  register: repo_state
- name: Remove rsync'd gentoo repo
  when: not repo_state.stat.exists
  ansible.builtin.file:
    path: "{{ gentoo_repo_base }}/gentoo"
    state: absent
- name: Add host portage configuration
  when: inventory_hostname not in groups["desktop"]
  ansible.builtin.include_tasks: add_configuration.yml
  vars:
    prefix: /etc/portage
    _portage_configuration: "{{ portage_configuration }}"
    _world: "{{ world + host_world }}"
- name: Add binhost portage configuration
  when:
    - inventory_hostname not in groups["desktop"]
    - podman_gentoo
  ansible.builtin.include_tasks: add_configuration.yml
  vars:
    prefix: /etc/podman-gentoo/base
    _portage_configuration: "{{ portage_configuration }}"
    _world: "{{ binhost_world }}"
