---
- name: Check if gentoo repo is a git repo
  ansible.builtin.stat:
    path: "{{ gentoo_repo_base }}/gentoo/.git"
  register: repo_state
- name: Remove rsync'd gentoo repo
  when: not repo_state.stat.exists
  ansible.builtin.file:
    path: "{{ gentoo_repo_base }}/gentoo"
    state: absent
- name: Apply portage configuration
  when: conf_type.value
  ansible.builtin.include_tasks: "{{ conf_type.key }}.yml"
  loop: "{{ portage_configuration[ansible_architecture] | dict2items }}"
  loop_control:
    loop_var: conf_type
