---
- name: Set make.profile symlink
  ansible.builtin.file:
    src: "/var/db/repos/gentoo/profiles/{{ conf_type.value }}"
    dest: /etc/portage/make.profile
    state: link
    owner: root
    group: root
