---
# TODO: We maybe want to validate the vars passed here eventually,
# but:
# Bug: https://github.com/ansible/ansible/issues/74995
# Workaround:
# yamllint disable-line
# https://stackoverflow.com/questions/51873965/check-that-only-one-of-several-ansible-variables-is-defined
# TODO: We also probably want a way to "reset" the firewall state to
# properly handle removing services. Is there a way to start fresh
# every run then make that configuration runtime+permanent at the end?
- name: Create firewalld service directory
  when: service_file is defined
  ansible.builtin.file:
    state: directory
    path: /etc/firewalld/services
    owner: root
    group: root
    mode: "0755"
- name: Add firewalld service definition file
  when: service_file is defined
  notify: Reload firewalld
  ansible.builtin.copy:
    src: "{{ service_file }}"
    dest: /etc/firewalld/services
    owner: root
    group: root
    mode: "0644"
- name: Flush handlers (reload firewalld for changed services)
  ansible.builtin.meta: flush_handlers
- name: Add service to specified zone
  when: service is defined
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    state: enabled
    service: "{{ service }}"
    zone: "{{ zone | default('public') }}"
- name: Add port(s) to specified zone
  when: port is defined
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    state: enabled
    port: "{{ port }}"
    zone: "{{ zone | default('public') }}"
- name: Add rich rule to specified zone
  when: rich_rule is defined
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    state: enabled
    rich_rule: "{{ rich_rule }}"
    zone: "{{ zone | defautl('public') }}"
