---
dependencies:
  - role: firewalld_service
    vars:
      zone: trusted
      service: prometheus-node-exporter
  - role: consul_service
    vars:
      service: node_exporter
      port: "{{ node_exporter_port }}"
    when: node_exporter or node_exporter_container
