---
- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
# TODO: this should probably be available globally
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
