---
- name: Link resolv.conf to resolved's stub
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    owner: systemd-resolve
    group: systemd-resolve
    mode: "0644"
    state: link
    force: true
- name: Install resolved configuration
  notify: Restart systemd-resolved
  ansible.builtin.copy:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: "0644"
- name: Start and enable resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: started
    enabled: true
