---
- name: Add nut ups configuration
  notify: Restart nut-server
  ansible.builtin.copy:
    src: ups.conf
    dest: /etc/nut/ups.conf
    owner: root
    group: root
    mode: "0644"
- name: Start and enable nut services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - nut-driver
    - nut-server
