---
- name: get gpg key
  ansible.builtin.shell:
    cmd: curl https://ajak.xyz/ajak.pub | gpg --import
  register: curl_result
  changed_when: "'imported' in curl_result.stderr"
- name: remove old ansible-pull cronjob
  ansible.builtin.file:
    path: /etc/cron.daily/ansible-pull
    state: absent
- name: remove wrongly named ansible-pull script
  ansible.builtin.file:
    path: /usr/local/bin/ansible-pull
    state: absent
- name: install ansible-pull script
  ansible.builtin.template:
    src: ansible-pull.j2
    dest: /usr/local/bin/ansiblepull
    mode: 0744
    owner: root
    group: root
- name: install ansible-pull cronjob
  ansible.builtin.copy:
    content: |
      PATH="/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"

      0 */6 * * * root /usr/local/bin/ansiblepull
    dest: /etc/cron.d/ansible-pull
    mode: 0644
    owner: root
    group: root
- name: add secrets repo
  ansible.builtin.git:
    repo: "{{ secrets_repo }}"
    dest: /etc/ansible-secrets
- name: register ansible repo
  ansible.builtin.stat:
    path: /etc/ansible-pull
  register: dir_info
- name: ensure ansible-pull repo has correct URL
  when: dir_info.stat.exists
  ansible.builtin.git:
    repo: "{{ this_repo }}"
    dest: /etc/ansible-pull
    version: main
