---
- name: Install torrc
  notify: Restart tor
  ansible.builtin.copy:
    src: torrc
    dest: /etc/tor/torrc
    owner: root
    group: root
    mode: "0755"
- name: Create tor service drop-in directory
  ansible.builtin.file:
    path: /etc/systemd/system/tor.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Add tor service drop-in
  notify:
    - Reload systemd
    - Restart tor
  ansible.builtin.copy:
    src: override.conf
    dest: /etc/systemd/system/tor.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
- name: Enable tor
  ansible.builtin.service:
    name: tor
    state: started
    enabled: true
