---
- name: Allow users in wheel to sudo
  ansible.builtin.lineinfile:
    regex: "%wheel ALL=(ALL) ALL"
    path: /etc/sudoers
    line: "%wheel ALL=(ALL) ALL"
    owner: root
    group: root
    mode: 0440
