---
- name: Create prometheus and alertmanager config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  with_items:
    - "{{ prom_confdir }}"
    - "{{ prom_confdir }}/alerts"
    - "{{ am_confdir }}"
- name: Create prometheus data directory
  ansible.builtin.file:
    path: "{{ prom_datadir }}"
    state: directory
    owner: nobody
    group: nobody
    mode: "0755"
- name: Install prometheus.yml
  notify: Restart prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prom_confdir }}/prometheus.yml"
    owner: root
    group: root
    mode: "0644"
    # validate: promtool check config %s
- name: Install prometheus alerts
  notify: Restart prometheus
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ prom_confdir }}/alerts/{{ item | basename }}"
    owner: root
    group: root
    mode: "0644"
    # validate: promtool check config %s
  with_fileglob:
    - alerts/*
- name: Install alertmanager config
  notify: Restart alertmanager
  ansible.builtin.template:
    src: am_config.yml.j2
    dest: "{{ am_confdir }}/alertmanager.yml"
    owner: root
    group: root
    mode: "0644"
    # validate: amtool check-config %s
- name: Install ntfy-alertmanager config
  ansible.builtin.template:
    src: ntfy-alertmanager.cfg.j2
    dest: "{{ am_confdir }}/ntfy-alertmanager.cfg"
    owner: root
    group: root
    mode: "0644"
- name: Install docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ prom_confdir }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"
- name: Run docker compose application stack
  community.docker.docker_compose_v2:
    project_src: "{{ prom_confdir }}"
    pull: always
    state: present
