---
- name: create prometheus config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ prom_confdir }}"
    - "{{ prom_confdir }}/alerts"
    - "{{ am_confdir }}"
    - "{{ am_confdir }}/template"
- name: create prometheus data directory
  ansible.builtin.file:
    path: "{{ prom_datadir }}"
    state: directory
    owner: nobody
    group: nobody
    mode: 0755
- name: install prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prom_confdir }}/prometheus.yml"
    owner: root
    group: root
    mode: 0644
    # validate: promtool check config %s
- name: install prometheus alerts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ prom_confdir }}/alerts/{{ item | basename }}"
    owner: root
    group: root
    mode: 0644
    # validate: promtool check config %s
  with_fileglob:
    - alerts/*
- name: install alertmanager config
  ansible.builtin.template:
    src: am_config.yml.j2
    dest: "{{ am_confdir }}/alertmanager.yml"
    owner: root
    group: root
    mode: 0644
    # validate: amtool check-config %s
- name: install docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ prom_confdir }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
- name: run prometheus and alertmanager
  docker_compose:
    project_src: "{{ prom_confdir }}"
    pull: true
    build: true
    state: present
