---
# TODO: somehow reorganize to not duplicate work between git and ansible
# Only sometimes host stuff is in Git. Maybe automate?
- name: Pull /etc/portage
  when: portage_git
  ansible.builtin.git:
    repo: git@git.ajak.xyz:ajak/etc-portage.git
    dest: /etc/portage
    update: true
    version: master
    accept_newhostkey: true
- name: Run global portage update
  ansible.builtin.include_role:
    tasks_from: global
    name: portage
