---
- name: Install dnsmasq.conf
  notify: Restart dnsmasq
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    validate: dnsmasq --test --conf-file=%s
    owner: root
    group: root
    mode: 0644
- name: Install authoritative records conf file
  notify: Restart dnsmasq
  ansible.builtin.template:
    src: dnsmasq-zones.conf.j2
    dest: /etc/dnsmasq-zones.conf
    validate: dnsmasq --test --conf-file=%s
    owner: root
    group: root
    mode: 0644
- name: Install systemd service drop-in to support auth-server
  notify:
    - Restart dnsmasq
    - Reload systemd
  ansible.builtin.copy:
    src: override.conf
    dest: /etc/systemd/system/dnsmasq.service.d/override.conf
    owner: root
    group: root
    mode: 0644
- name: Start and enable dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true
