---
- name: Deploy dns server stack
  when: dnsserver
  block:
    # dnscrypt-proxy for handling outbound requests
    # unbound for handling local zone
    # pihole for filtering
    - name: Setup docker network
      ansible.builtin.include_tasks: network.yml
    - name: Deploy dnscrypt-proxy
      ansible.builtin.include_tasks: dnscryptproxy.yml
    - name: Deploy unbound
      ansible.builtin.include_tasks: unbound.yml
    - name: Deploy pihole
      ansible.builtin.include_tasks: pihole.yml
