---
- name: create homeassistant's git repo
  notify: restart homeassistant
  block:
    - name: create homeassistant's git repo
      git:
        repo: "{{ ha_repo }}"
        dest: "{{ ha_confdir }}"
        clone: true
        update: true
        accept_newhostkey: true
    - name: deploy homeassistant
      docker_compose:
        project_src: "{{ ha_confdir }}"
        pull: true
        build: true
        state: present
