---
- name: Add homeassistant's configuration
  ansible.builtin.template:
    src: configuration.yaml.j2
    dest: "{{ ha_confdir }}/configuration.yaml"
    owner: root
    group: root
    mode: "0644"
  register: conf
# Formerly this was done using a docker-compose.yml thrown into git
# somewhere. We can't easily control labels for traefik this way, so
# we instead manage the container directly
- name: Start the homeassistant container
  # mostly grokked out of:
  # https://www.home-assistant.io/installation/linux#install-home-assistant-container
  community.docker.docker_container:
    name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    pull: true
    privileged: true
    state: started
    restart_policy: unless-stopped
    network_mode: traefik
    exposed_ports:
      - 8123
    labels:
      traefik.http.routers.ha.rule: Host(`ha.{{ public_domain }}`)
      traefik.http.routers.ha.tls: "true"
      traefik.http.routers.ha.tls.certresolver: myresolver
    volumes:
      - "{{ ha_confdir }}:/config"
      - /etc/localtime:/etc/localtime:ro
    # Hacky, but if we used a handler for the configuration we'd have
    # to duplicate this entire task into a handler.
    restart: "{{ conf.changed }}"
