---
- name: add traefik
  include_tasks: traefik.yml
  when: traefik
- name: add mervin
  include_tasks: mervin.yml
  when: mervin
- name: add homeassistant
  include_tasks: homeassistant.yml
  when: homeassistant
