---
# Doesn't seem fixed: https://github.com/progval/Limnoria/issues/1516
# - name: Add mervin
#   ansible.builtin.include_tasks: mervin.yml
#   when: mervin
- name: Add homeassistant
  ansible.builtin.include_tasks: homeassistant.yml
  when: homeassistant
- name: Add cron job to prune Docker data
  # TODO: this is hacky, should put the above in their own roles (and
  # specify dependencies on traefik appropriately) then use this
  # docker role to do generate configuration like this:
  when: mervin or homeassistant
  ansible.builtin.copy:
    src: docker-system-prune
    dest: /etc/cron.daily/docker-system-prune
    mode: 0755
    owner: root
    group: root
