---
- name: Add cron job to prune Docker data
  when: docker
  ansible.builtin.copy:
    src: docker-system-prune
    dest: /etc/cron.d/docker-system-prune
    mode: "0644"
    owner: root
    group: root
