---
- name: Add traefik
  ansible.builtin.include_tasks: traefik.yml
  when: traefik
- name: Add mervin
  ansible.builtin.include_tasks: mervin.yml
  when: mervin
- name: Add homeassistant
  ansible.builtin.include_tasks: homeassistant.yml
  when: homeassistant
