---
- name: deploy mervin
  notify: restart mervin
  block:
    - name: create mervin's git repo
      git:
        repo: "{{ mervin_repo }}"
        dest: "{{ mervin_confdir }}"
        clone: true
        update: true
        accept_newhostkey: true
    - name: update and build mervin's image
      docker_compose:
        project_src: "{{ mervin_confdir }}"
        pull: true
        build: true
        state: present
