---
- name: deploy mervin
  notify: restart mervin
  block:
    - name: create mervin's git repo
      git:
        repo: git@git.wg.home.arpa:ajak/mervin.git
        dest: /etc/mervin
        clone: true
        update: true
        accept_newhostkey: true
    - name: update and build mervin's image
      docker_compose:
        project_src: /etc/mervin
        pull: true
        build: true
        state: present
