---
- name: create traefik's configuration directory
  ansible.builtin.file:
    path: "{{ traefik_confdir }}"
    state: directory
    owner: root
    group: root
    mode: 0700
- name: add traefik's traefik.toml
  notify: restart traefik
  ansible.builtin.template:
    src: traefik/traefik.toml.j2
    dest: "{{ traefik_confdir }}/traefik.toml"
    owner: root
    group: root
    mode: 0600
- name: add traefik's docker-compose
  notify: restart traefik
  ansible.builtin.template:
    src: traefik/docker-compose.yml.j2
    dest: "{{ traefik_confdir }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0600
- name: create traefik network
  docker_network:
    name: traefik
- name: run traefik
  docker_compose:
    project_src: "{{ traefik_confdir }}"
    pull: true
    build: true
    state: present
