---
- name: Create traefik's configuration directory
  ansible.builtin.file:
    path: "{{ traefik_confdir }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
- name: Add traefik's traefik.toml
  notify: Restart traefik
  ansible.builtin.template:
    src: traefik.toml.j2
    dest: "{{ traefik_confdir }}/traefik.toml"
    owner: root
    group: root
    mode: "0600"
- name: Add traefik's extra configuration
  notify: Restart traefik
  when: traefik_proxy_for is defined
  ansible.builtin.template:
    src: extra.toml.j2
    dest: "{{ traefik_confdir }}/extra.toml"
    owner: root
    group: root
    mode: "0600"
- name: Add traefik's docker-compose
  notify: Restart traefik
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ traefik_confdir }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0600"
- name: Create traefik network
  community.docker.docker_network:
    name: "{{ network_name }}"
- name: Run traefik
  community.docker.docker_compose:
    project_src: "{{ traefik_confdir }}"
    pull: true
    build: true
    state: present
