---
- name: install dnscrypt-proxy configuration
  notify: restart dnscrypt-proxy
  when: dnscryptproxy
  block:
    - name: install dnscrypt-proxy.toml
      ansible.builtin.copy:
        src: dnscrypt-proxy.toml
        dest: /etc/dnscrypt-proxy/dnscrypt-proxy.toml
        mode: 0644
    - name: install cloaking-rules.txt
      ansible.builtin.template:
        src: cloaking-rules.txt.j2
        dest: /etc/dnscrypt-proxy/cloaking-rules.txt
- name: start and enable dnscrypt-proxy
  when: dnscryptproxy
  ansible.builtin.service:
    name: dnscrypt-proxy
    enabled: true
    state: started
