---
- name: Lookup system service variables
  ansible.builtin.set_fact:
    system_services_vars:
      "{{ q('ansible.builtin.varnames', 'system_services') }}"
- name: Lookup system services
  ansible.builtin.set_fact:
    system_services:
      "{{ lookup('ansible.builtin.vars', *system_services_vars) }}"
- name: Lookup system service variables
  ansible.builtin.set_fact:
    user_services_vars:
      "{{ q('ansible.builtin.varnames', 'user_services') }}"
- name: Lookup system services
  ansible.builtin.set_fact:
    user_services:
      "{{ lookup('ansible.builtin.vars', *user_services_vars) }}"
- name: Lookup system stop service variables
  ansible.builtin.set_fact:
    system_stop_services_vars:
      "{{ q('ansible.builtin.varnames', 'system_stop_services') }}"
- name: Lookup system stop services
  ansible.builtin.set_fact:
    system_stop_services:
      "{{ lookup('ansible.builtin.vars', *system_stop_services_vars) }}"
- name: Start and enable system services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ system_services }}"
- name: Start and enable user services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: user
  with_items: "{{ user_services }}"
  become_user: jake
  environment:
    # TODO - automatic detection of UID
    XDG_RUNTIME_DIR: "/run/user/1000"
- name: Stop and disable services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items: "{{ system_stop_services }}"
