---
- name: Debug
  ansible.builtin.debug:
    msg: "Adding these packages to world: {{ world_pkgs }}"
- name: Add packages to world
  portage: # noqa fqcn
    package: "{{ world_pkgs }}"
    noreplace: true
    getbinpkg: "{{ getpkg | default(false) }}"
    state: present
- name: Debug
  ansible.builtin.debug:
    msg: "Removing these packages from world: {{ depclean_pkgs }}"
- name: Depclean packages
  portage: # noqa fqcn
    package: "{{ depclean_pkgs }}"
    depclean: true
    getbinpkg: true
    state: absent
