---
- name: Debug
  ansible.builtin.debug:
    msg: "Adding these packages to world: {{ world_pkgs }}"
- name: Add packages to world
  portage: # noqa fqcn
    package: "{{ item }}"
    noreplace: true
    getbinpkg: "{{ getpkg | default(false) }}"
  loop: "{{ world_pkgs }}"
- name: Debug
  ansible.builtin.debug:
    msg: "Removing these packages from world: {{ depclean_pkgs }}"
- name: Add packages to world
  portage: # noqa fqcn
    package: "{{ item }}"
    depclean: true
    getbinpkg: true
    state: absent
  loop: "{{ depclean_pkgs }}"
