---
- name: Remove old ansible-pull cronjob
  ansible.builtin.file:
    path: /etc/cron.daily/ansible-pull
    state: absent
- name: Remove wrongly named ansible-pull script
  ansible.builtin.file:
    path: /usr/local/bin/ansible-pull
    state: absent
- name: Install ansible-pull script
  ansible.builtin.template:
    src: ansible-pull.j2
    dest: /usr/local/bin/ansiblepull
    mode: "0744"
    owner: root
    group: root
- name: Install ansible-pull cronjob
  ansible.builtin.copy:
    content: |
      PATH="/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"

      0 0 * * 0 root gpg --quiet --keyserver hkps://keys.gentoo.org --recv-keys 39333C79B7BD85CD55C02E4C812BDFCB974B5783 >/dev/null
      0 */6 * * * root /usr/local/bin/ansiblepull 2>&1 >/dev/null
    dest: /etc/cron.d/ansible-pull
    mode: "0644"
    owner: root
    group: root
- name: Add secrets repo
  ansible.builtin.git:
    repo: "{{ secrets_repo }}"
    dest: /etc/ansible-secrets
    version: main
    accept_newhostkey: true
- name: Register ansible repo
  ansible.builtin.stat:
    path: /etc/ansible-pull
  register: dir_info
- name: Ensure ansible-pull repo has correct URL
  when: dir_info.stat.exists
  ansible.builtin.git:
    repo: "{{ this_repo }}"
    dest: /etc/ansible-pull
    version: main
    accept_newhostkey: true
- name: Create ansible configuration directory
  ansible.builtin.file:
    path: /etc/ansible/
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Add ansible.cfg
  ansible.builtin.template:
    src: ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg
    owner: root
    group: root
    mode: "0644"
