---
- name: Install systemd-networkd configuration
  notify: Restart systemd-networkd
  ansible.builtin.template:
    src: 20-public.network.j2
    dest: /etc/systemd/network/20-public.network
    owner: root
    group: root
    mode: "0644"
- name: Remove old network files
  notify: Restart systemd-networkd
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/systemd/network/20-wired.network
    - /etc/systemd/network/20-private.network
- name: Start and enable systemd-networkd
  ansible.builtin.service:
    name: systemd-networkd
    enabled: true
    state: started
