---
- name: Install sshd configuration
  notify: Restart sshd
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    validate: sshd -tf %s
    owner: root
    group: root
    mode: "0600"
- name: Enable sshd
  ansible.builtin.service:
    name: sshd
    enabled: true
    state: started
