---
- name: install sshd configuration
  notify: restart sshd
  ansible.builtin.copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    validate: sshd -tf %s
- name: enable sshd
  ansible.builtin.service:
    name: sshd
    enabled: true
    state: started
